[2024-11-07 10:05:45,256][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,257][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-07 10:05:45,258][root][INFO] - Command line args:
ansatz.alpha=1
task=train
[2024-11-07 10:05:45,258][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,260][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 500
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-07 10:05:45,260][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,261][root][CRITICAL] - Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grad_sample'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'grad_sample.tasks.fullsum_train.Trainer':
ModuleNotFoundError("No module named 'grad_sample'")
Are you sure that module 'grad_sample' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
[2024-11-07 10:05:45,681][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,682][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-07 10:05:45,683][root][INFO] - Command line args:
ansatz.alpha=2
task=train
[2024-11-07 10:05:45,684][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,685][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 500
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 2
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-07 10:05:45,686][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:05:45,687][root][CRITICAL] - Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grad_sample'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'grad_sample.tasks.fullsum_train.Trainer':
ModuleNotFoundError("No module named 'grad_sample'")
Are you sure that module 'grad_sample' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
