[2024-11-05 18:08:12,717][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:08:12,718][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-05 18:08:12,718][root][INFO] - Command line args:

[2024-11-05 18:08:12,719][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:08:12,721][root][INFO] - Run config:
device: '4'
solver_fn: nk.optimizer.solver.cholesky
lr: 0.0001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-05 18:08:12,721][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:08:15,493][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-11-05 18:08:15,494][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2024-11-05 18:08:23,670][root][CRITICAL] - the first argument must be callable
Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 52, in main
    task()
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_train.py", line 21, in __call__
    self.gs.run(n_iter=self.n_iter, out=(self.json_log, self.state_log), callback=(save_cb,))
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/driver/abstract_variational_driver.py", line 333, in run
    for step in self.iter(n_iter, step_size):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/driver/abstract_variational_driver.py", line 226, in iter
    self._dp = self._forward_and_backward()
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/driver/vmc.py", line 124, in _forward_and_backward
    self._dp = self.preconditioner(self.state, self._loss_grad, self.step_count)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/utils/timing.py", line 230, in timed_function
    return fun(*args, **kwargs)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/optimizer/preconditioner.py", line 119, in __call__
    self.x0, self.info = self._lhs.solve(self.solver, gradient, x0=x0)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/utils/timing.py", line 230, in timed_function
    return fun(*args, **kwargs)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/netket/optimizer/linear_operator.py", line 103, in solve
    return self._solve(jax.tree_util.Partial(solve_fun), y, x0=x0, **kwargs)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/tree_util.py", line 556, in __new__
    return super().__new__(klass, func, *args, **kw)
TypeError: the first argument must be callable
