[2024-11-06 10:59:17,803][root][INFO] - ---------------------------------------------------------------
[2024-11-06 10:59:17,804][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-06 10:59:17,805][root][INFO] - Command line args:

[2024-11-06 10:59:17,805][root][INFO] - ---------------------------------------------------------------
[2024-11-06 10:59:17,807][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_analysis.FullSumPruning

[2024-11-06 10:59:17,808][root][INFO] - ---------------------------------------------------------------
[2024-11-06 10:59:20,342][root][CRITICAL] - Error in call to target 'grad_sample.tasks.fullsum_analysis.FullSumPruning':
TypeError("descriptor '__init__' requires a 'super' object but received a 'DictConfig'")
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 19, in __init__
    super.__init__(cfg)
TypeError: descriptor '__init__' requires a 'super' object but received a 'DictConfig'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'grad_sample.tasks.fullsum_analysis.FullSumPruning':
TypeError("descriptor '__init__' requires a 'super' object but received a 'DictConfig'")
full_key: task
